version: '3.7'

services:
  kafka:
    image: wurstmeister/kafka:2.13-2.8.0
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
      - zookeeper

  zookeeper:
    image: wurstmeister/zookeeper:latest
    container_name: zookeeper
    ports:
      - "2181:2181"

  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: AliJokar
      POSTGRES_PASSWORD: A1234
      POSTGRES_DB: my_database
    volumes:
      - postgres_data:/var/lib/postgresql/data

  your_service_name:
    build:
      context: .
    container_name: my_service
    volumes:
      - ./codes:/codes
    depends_on:
      - kafka
      - postgres

volumes:
  postgres_data:
